name: Lending Market CI
on: [pull_request]

jobs:
  typo_check:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2

    - name: Writes changes in the local checkout
      uses: crate-ci/typos@master
      with: 
        write_changes: true

  test_lending_market:
    name: Test lending_market
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          # rustup update
          # rustup component add clippy
          # rustup install nightly 
          rustup default 1.69.0   
          git clone https://github.com/radixdlt/radixdlt-scrypto.git
          cd radixdlt-scrypto
          cargo install --path ./simulator         

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version   
          scrypto --version

      - name: Build
        run: |
          cd lending_market
          scrypto build     

      - name: Lint lending_market
        run: |
          cd lending_market
          cargo fmt -- --check
          cargo clippy -- -D warnings          

      - name: Test lending_market
        run: |
          cd lending_market
          cargo check
          cargo test --all    
